In [1]:
import pandas as pd
%store -r writeoff

In [2]:
writeoff.head()

,Provider Name,Specialty,Department Name,Adjustment Name,Adjustments
0,Provider 478,Surgery: Plastic and Reconstruction,Dept 839,Contractual,259428.2080
1,Provider 627,Cardiology: Interventional,Dept 233,Contractual,220272.8320
2,Provider 2349,Cardiology: Noninvasive,Dept 336,Contractual,218104.0746
3,Provider 627,Cardiology: Interventional,Dept 233,Contractual,197405.6280
4,Provider 804,Surgery: Neurological,Dept 168,Contractual,189671.1010

In [8]:
writeoff.groupby(['Provider Name', 'Specialty'])['Adjustments'].sum().to_frame()

                                                       Adjustments
Provider Name Specialty
Provider 1    Cardiology: Interventional             265393.695900
Provider 10   NP: Pediatric/Child Health               1148.316086
Provider 100  Pediatrics: Neonatal Medicine          138967.769450
Provider 1000 PA: Family Medicine (without OB)         2481.556750
Provider 1002 Cardiology: Electrophysiology           38897.298600
...                                                            ...
Provider 994  Surgery: Plastic and Reconstruction      2678.242500
Provider 995  PA: Family Medicine (without OB)         1088.368000
Provider 997  Pediatrics: Critical Care/Intensivist  135132.244650
Provider 998  Pediatrics: Gastroenterology           100886.148400
Provider 999  Internal Medicine: General                 50.546250

[2969 rows x 1 columns]

In [17]:
writeoff[writeoff['Adjustment Name'].str.contains('Timely Filing')] #12884

,Provider Name,Specialty,Department Name,Adjustment Name,Adjustments
357,Provider 1829,Cardiology: Electrophysiology,Dept 594,Timely Filing,48475.2000
1007,Provider 1829,Cardiology: Electrophysiology,Dept 594,Timely Filing,25174.2700
1069,Provider 478,Surgery: Plastic and Reconstruction,Dept 839,Timely Filing,24202.9967
1226,Provider 478,Surgery: Plastic and Reconstruction,Dept 839,Timely Filing,22175.4614
1299,Provider 827,Pediatrics: Neonatal Medicine,Dept 603,Timely Filing,21219.7500
...,...,...,...,...,...
79994,Provider 994,Surgery: Plastic and Reconstruction,Dept 1073,Timely Filing,0.0000
79995,Provider 994,Surgery: Plastic and Reconstruction,Dept 1073,Timely Filing,0.0000
79996,Provider 994,Surgery: Plastic and Reconstruction,Dept 1073,Timely Filing,0.0000
79998,Provider 999,Internal Medicine: General,Dept 129,Timely Filing,0.0000
79999,Provider 999,Internal Medicine: General,Dept 129,Timely Filing,0.0000

## SPECIALTY

In [75]:
rpt = writeoff[writeoff['Adjustment Name'].str.contains('Timely Filing')]
rpt = rpt.groupby("Specialty").apply(
    lambda d: pd.Series(
        {
            
            "Distinct Provider": d["Provider Name"].nunique(),
            "Sum of Timely Filing": d["Adjustments"].sum(),
            "TF per Provider":d["Adjustments"].sum() / d["Provider Name"].nunique()
           
          
        }
    )).sort_values(by="TF per Provider", ascending=False)

rpt.loc['Total'] = pd.Series(rpt[["Distinct Provider", "Sum of Timely Filing","TF per Provider"]]
                   .sum(), index = ["Distinct Provider", "Sum of Timely Filing","TF per Provider"])
rpt.style.format({"Distinct Provider": "{:20,.0f}", 
                    "Sum of Timely Filing": "${:20,.2f}", 
                    "TF per Provider": "${:20,.2f}"}).format_index(str.upper, axis=1).background_gradient(cmap='Reds')

## DEPARTMENT

In [89]:
rpt1 = writeoff[writeoff['Adjustment Name'].str.contains('Timely Filing')]
rpt1 = rpt1.groupby("Department Name").apply(
    lambda d: pd.Series(
        {
            "Sum of Timely Filing": d["Adjustments"].sum(),
            "Distinct Provider": d["Provider Name"].nunique(),
            "TF Per Provider":d["Adjustments"].sum() / d["Provider Name"].nunique(),
            "YEARLY COST OF TIMELY FILING": d["Adjustments"].sum() * 4
        }
    )).sort_values(by="Sum of Timely Filing", ascending=False)

rpt1.loc['Total'] = pd.Series(rpt1[["Sum of Timely Filing","Distinct Provider", "TF Per Provider", "YEARLY COST OF TIMELY FILING"]]
                 .sum(), index = ["Sum of Timely Filing", "Distinct Provider","TF Per Provider", "YEARLY COST OF TIMELY FILING"])

rpt1.style.format({ "Sum of Timely Filing": "${:20,.2f}", 
                    "Distinct Provider": "{:20,.0f}",
                    "TF Per Provider": "${:20,.2f}",
                    "YEARLY COST OF TIMELY FILING":"${:20,.2f}"}).format_index(str.upper, axis=1).background_gradient(cmap='Reds')

## POTENTIAL SAVINGS

In [90]:
rpt1 = writeoff[writeoff['Adjustment Name'].str.contains('Timely Filing')]
rpt1 = rpt1.groupby("Department Name").apply(
    lambda d: pd.Series(
        {
            "Sum of Timely Filing": d["Adjustments"].sum(),
            "Distinct Provider": d["Provider Name"].nunique(),
            "TF Per Provider":d["Adjustments"].sum() / d["Provider Name"].nunique(),
            "YEARLY COST OF TIMELY FILING": d["Adjustments"].sum() * 4
        }
    )).sort_values(by="Sum of Timely Filing", ascending=False).head(5)

rpt1.loc['Total'] = pd.Series(rpt1[["Sum of Timely Filing","Distinct Provider", "TF Per Provider", "YEARLY COST OF TIMELY FILING"]]
                 .sum(), index = ["Sum of Timely Filing", "Distinct Provider","TF Per Provider", "YEARLY COST OF TIMELY FILING"])

rpt1.style.format({ "Sum of Timely Filing": "${:20,.2f}", 
                    "Distinct Provider": "{:20,.0f}",
                    "TF Per Provider": "${:20,.2f}",
                    "YEARLY COST OF TIMELY FILING":"${:20,.2f}"}).format_index(str.upper, axis=1).background_gradient(cmap='Reds')